### PR TITLE
fix: error when transforming json models unsupported by the DSL

### LINKED ISSUE #59: Language incorrectly transforms JSON syntax that is not supported in the DSL
For example, the below currently cannot be represented in JSON

```json
{
  "schema_version": "1.1",
  "type_definitions": [
    {
      "type": "user",
      "relations": {}
    },
    {
      "type": "folder",
      "relations": {
        "admin": {
          "this": {}
        },
        "viewer": {
          "this": {}
        },
        "blocked": {
          "this": {}
        },
        "can_view": {
          "union": {
            "child": [
              {
                "computedUserset": {
                  "object": "",
                  "relation": "admin"
                }
              },
              {
                "difference": {
                  "base": {
                    "computedUserset": {
                      "object": "",
                      "relation": "viewer"
                    }
                  },
                  "subtract": {
                    "computedUserset": {
                      "object": "",
                      "relation": "blocked"
                    }
                  }
                }
              }
            ]
          }
        }
      },
      "metadata": {
        "relations": {
          "admin": {
            "directly_related_user_types": [
              {
                "type": "user"
              }
            ]
          },
          "viewer": {
            "directly_related_user_types": [
              {
                "type": "user"
              }
            ]
          },
          "blocked": {
            "directly_related_user_types": [
              {
                "type": "user"
              }
            ]
          },
          "can_view": {
            "directly_related_user_types": []
          }
        }
      }
    }
  ]
}
```

and the language transforms it to: 
```py
model
  schema 1.1

type user

type folder
  relations
    define admin: [user]
    define blocked: [user]
    define can_view: admin or
    define viewer: [user]
```

### PR DESCRIPTION
**Pull request by rhamzeh**
## References

- closes #59 

## Review Checklist
- [x] I have clicked on ["allow edits by maintainers"](https://docs.github.com/en/pull-requests/collaborating-with-pull-requests/working-with-forks/allowing-changes-to-a-pull-request-branch-created-from-a-fork).
- [ ] I have added documentation for new/changed functionality in this PR or in a PR to [openfga.dev](https://github.com/openfga/openfga.dev) [Provide a link to any relevant PRs in the references section above]
- [x] The correct base branch is being used, if not `main`
- [x] I have added tests to validate that the change in functionality is working as expected

### CODE REVIEW

File: pkg/go/transformer/dsltojson.go [hunk 1]
```diff
@@ -103,7 +103,6 @@ func (l *OpenFgaDslListener) ExitRelationDeclaration(ctx *parser.RelationDeclara
 					},
 				},
 			}
-			break
```
Comment (adriantam) [inline pkg/go/transformer/dsltojson.go:106]: why remove break?  You mean it to be fall through switch/case logic?

Comment (rhamzeh) [reply pkg/go/transformer/dsltojson.go:106]: Unlike JS and Java, Go does not need `break` between cases - you only use it if you need to break early, it does not have auto fallback to other cases.

**Review by adriantam — APPROVED** [review]
